name: Repository Events
on: [push, pull_request, issues]
jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Check Github environment variables
                run: |
                    echo $GITHUB_SHA
                    echo $GITHUB_REF
            -   name: Git Checkout
                uses: actions/checkout@v4