name: External Events
on:
    repository_dispatch:
        types: [build]

jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.event.client_payload.unit }}"


            # curl -L \                                                                                                                                                                               ─╯
            # -X POST \
            # -H "Accept: application/vnd.github+json" \
            # -H "Authorization: Bearer <TOKEN>" \
            # -H "X-GitHub-Api-Version: 2022-11-28" \
            # https://api.github.com/repos/github-actions-demos/random-tests/dispatches \
            # -d '{"event_type":"build","client_payload":{"unit":false,"integration":true}}'